version: '3'
services:
  fresh-server:
    ports:
      - 8888:80  # 左边是宿主机端口，右边docker内部端口
    build: .
    env_file:
      - .env
    extra_hosts:
      - "www.dailyfresh.com:0.0.0.0"   # 左边域名，右边域名解析地址，只是给docker用的。外边向内访问，只能是通过宿主机的host文件做操作。
    volumes:
      - .:/work   # 映射docker内部文件夹
    environment:
      - DEBUG=true
      - DEBUG_SERVER=true   # 用于服务器auto reload模式指定(非开发模式，请勿开启)
    working_dir: /work

  mysql:
    image: "mysql:5.7.20"
    ports:
      - 4444:3306
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=mysql
    volumes:
    - ./_db:/var/lib/mysql
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    networks:
    - fresh_net

  adminer:
    image: "adminer:4.6.2"
    ports:
    - 8081:8080
    networks:
    - fresh_net
#
#  redis:
#    image: 'redis:latest'
#
#    volumes:
##    - ./redis_data:/data
#    - ./redis.conf:/usr/local/etc/redis/redis.conf
#    #    ports:
#    #      - 6379:6379
#    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
#    networks:
#    - fresh_net

networks:
  fresh_net:
    external: true
