version: '3'
services:
  dbtools:
    build: ""
    volumes:
      - .:/work
    ports:
      - 8866:8866
    environment:
      - DB_NAME=freshProjectaaaaa
      - DB_USER=root
      - DB_PASSWORD=123456
#      - DB_HOST=0.0.0.0
      - DB_HOST=mysql
      - DEBUG=True
    networks:
      - fresh_net

networks:
  fresh_net:
    external: true


